from __future__ import annotations

from copy import deepcopy

FONT_SIZES = [11, 12, 13, 14, 15, 16]
FONT_SIZE_DEFAULT = 12


def _with_legacy_aliases(tokens: dict[str, str]) -> dict[str, str]:
    # Compatibility shim kept as an identity function so theme definitions stay concise.
    return dict(tokens)


_THEME_TOKENS: dict[str, dict[str, str]] = {
    "dark": _with_legacy_aliases(
        {
            # Surface system (Digital Architect spec).
            "surface_dim": "#0c0e11",
            "surface": "#0c0e11",
            "surface_container_lowest": "#0c0e11",
            "surface_container_low": "#111417",
            "surface_container": "#171a1d",
            "surface_container_high": "#1d2024",
            "surface_container_highest": "#23262a",
            "surface_variant": "#2b2f35",
            # Content colors.
            "on_surface": "#f9f9fd",
            "on_surface_variant": "#aaabaf",
            "on_surface_muted": "#858890",
            # Brand/intent palette.
            "primary": "#8dacff",
            "primary_hover": "#a2bdff",
            "primary_dim": "#5f79bf",
            "primary_alpha_05": "rgba(141,172,255,13)",
            "primary_alpha_15": "rgba(141,172,255,38)",
            "primary_alpha_25": "rgba(141,172,255,64)",
            "secondary": "#b686ff",
            "secondary_dim": "#8e62cc",
            "tertiary": "#a1faff",
            "tertiary_container": "#2e6f75",
            "secondary_container": "#33234a",
            "on_secondary_container": "#ebdcff",
            "on_primary_fixed": "#000000",
            "success": "#40c057",
            "warning": "#f59f00",
            "error_dim": "#d73357",
            # Outlines/selection.
            "outline": "#5a5d62",
            "outline_variant": "#46484b",
            "outline_20": "rgba(90,93,98,51)",
            "outline_ghost": "rgba(70,72,75,38)",
            "selection": "#304166",
            # Typography.
            "font_family_body": "'Inter', 'Segoe UI', 'SF Pro Text', sans-serif",
            "font_family_display": "'Space Grotesk', 'Inter', 'Segoe UI', sans-serif",
            "font_family_mono": "'JetBrains Mono', 'Inter', 'SF Mono', monospace",
            # Spacing/radius tokenization (0.2rem base approximated for desktop Qt).
            "spacing_1": "2px",
            "spacing_2": "4px",
            "spacing_3": "6px",
            "spacing_4": "9px",
            "spacing_5": "12px",
            "spacing_6": "14px",
            "spacing_8": "28px",
            "spacing_16": "56px",
            "rounded_sm": "2px",
            "rounded_md": "6px",
            "rounded_full": "9999px",
            # Block type colors.
            "type_empty": "#6b7280",
            "type_container": "#5a6b88",
            "type_image": "#5b8bde",
            "type_video": "#d86b6b",
            "type_audio": "#4aa88f",
            "type_text": "#6d7894",
            "type_prompt": "#d29447",
            "type_badge_text": "#f8fafc",
        }
    ),
    "dim": _with_legacy_aliases(
        {
            "surface_dim": "#101320",
            "surface": "#101320",
            "surface_container_lowest": "#080a0f",
            "surface_container_low": "#161b2b",
            "surface_container": "#1e2335",
            "surface_container_high": "#272d43",
            "surface_container_highest": "#2f3751",
            "surface_variant": "#353f5d",
            "on_surface": "#edf1ff",
            "on_surface_variant": "#afb7d6",
            "on_surface_muted": "#7f88aa",
            "primary": "#8dacff",
            "primary_hover": "#aec4ff",
            "primary_dim": "#607abc",
            "primary_alpha_05": "rgba(141,172,255,13)",
            "primary_alpha_15": "rgba(141,172,255,38)",
            "primary_alpha_25": "rgba(141,172,255,64)",
            "secondary": "#b686ff",
            "secondary_dim": "#8e62cc",
            "tertiary": "#a1faff",
            "tertiary_container": "#2b6872",
            "secondary_container": "#3a2c54",
            "on_secondary_container": "#ebdcff",
            "on_primary_fixed": "#000000",
            "success": "#40c057",
            "warning": "#f59f00",
            "error_dim": "#d73357",
            "outline": "#626a87",
            "outline_variant": "#464d66",
            "outline_20": "rgba(98,106,135,51)",
            "outline_ghost": "rgba(70,77,102,38)",
            "selection": "#3f5078",
            "font_family_body": "'Inter', 'Segoe UI', 'SF Pro Text', sans-serif",
            "font_family_display": "'Space Grotesk', 'Inter', 'Segoe UI', sans-serif",
            "font_family_mono": "'JetBrains Mono', 'Inter', 'SF Mono', monospace",
            "spacing_1": "2px",
            "spacing_2": "4px",
            "spacing_3": "6px",
            "spacing_4": "9px",
            "spacing_5": "12px",
            "spacing_6": "14px",
            "spacing_8": "28px",
            "spacing_16": "56px",
            "rounded_sm": "2px",
            "rounded_md": "6px",
            "rounded_full": "9999px",
            "type_empty": "#6b7280",
            "type_container": "#5a6b88",
            "type_image": "#5b8bde",
            "type_video": "#d86b6b",
            "type_audio": "#4aa88f",
            "type_text": "#6d7894",
            "type_prompt": "#d29447",
            "type_badge_text": "#f8fafc",
        }
    ),
    "light": _with_legacy_aliases(
        {
            "surface_dim": "#f1f3f7",
            "surface": "#f1f3f7",
            "surface_container_lowest": "#e6e8ed",
            "surface_container_low": "#ebedf2",
            "surface_container": "#ffffff",
            "surface_container_high": "#f5f6f9",
            "surface_container_highest": "#ffffff",
            "surface_variant": "#e2e5eb",
            "on_surface": "#1d1f23",
            "on_surface_variant": "#5c5f66",
            "on_surface_muted": "#767982",
            "primary": "#5a7fd4",
            "primary_hover": "#7194e5",
            "primary_dim": "#4566ad",
            "primary_alpha_05": "rgba(90,127,212,13)",
            "primary_alpha_15": "rgba(90,127,212,38)",
            "primary_alpha_25": "rgba(90,127,212,64)",
            "secondary": "#8862cc",
            "secondary_dim": "#6e4fa5",
            "tertiary": "#258f9a",
            "tertiary_container": "#b7edf1",
            "secondary_container": "#e9dfff",
            "on_secondary_container": "#2d1f47",
            "on_primary_fixed": "#000000",
            "success": "#2f9e44",
            "warning": "#e67700",
            "error_dim": "#d73357",
            "outline": "#b1b6c0",
            "outline_variant": "#c1c4cb",
            "outline_20": "rgba(95,103,117,51)",
            "outline_ghost": "rgba(95,103,117,38)",
            "selection": "#c9d6f2",
            "font_family_body": "'Inter', 'Segoe UI', 'SF Pro Text', sans-serif",
            "font_family_display": "'Space Grotesk', 'Inter', 'Segoe UI', sans-serif",
            "font_family_mono": "'JetBrains Mono', 'Inter', 'SF Mono', monospace",
            "spacing_1": "2px",
            "spacing_2": "4px",
            "spacing_3": "6px",
            "spacing_4": "9px",
            "spacing_5": "12px",
            "spacing_6": "14px",
            "spacing_8": "28px",
            "spacing_16": "56px",
            "rounded_sm": "2px",
            "rounded_md": "6px",
            "rounded_full": "9999px",
            "type_empty": "#6b7280",
            "type_container": "#64748b",
            "type_image": "#2563eb",
            "type_video": "#b91c1c",
            "type_audio": "#0f766e",
            "type_text": "#475569",
            "type_prompt": "#b45309",
            "type_badge_text": "#ffffff",
        }
    ),
}

THEME_NAMES = list(_THEME_TOKENS.keys())


def theme_tokens(name: str) -> dict[str, str]:
    return deepcopy(_THEME_TOKENS.get(name, _THEME_TOKENS["dark"]))
